#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Increment patch version (no tag, no commit)
npm version patch --no-git-tag-version

# Add updated version files to the current commit
git add package.json package-lock.json

