const fs = require('fs');
const path = require('path');

try {
  // Read package.json to get the version
  // Assuming this script is running from the root or .husky directory,
  // we try to locate package.json from the project root.
  // The current working directory when git hooks run is usually the repo root.
  const pkgPath = path.resolve(process.cwd(), 'package.json');
  if (!fs.existsSync(pkgPath)) {
    console.error('package.json not found at', pkgPath);
    process.exit(0);
  }

  const pkg = require(pkgPath);
  
  // generated by git
  const commitMsgFile = process.argv[2]; 
  if (!commitMsgFile) {
    // No message file provided?
    process.exit(0);
  }

  let msg = fs.readFileSync(commitMsgFile, 'utf8');
  const version = pkg.version;
  const versionPrefix = 'v' + version;
  
  // precise regex to match "vX.Y.Z " at the start
  const versionRegex = /^v\d+\.\d+\.\d+\s+/;
  
  if (versionRegex.test(msg)) {
    // Update existing version
    msg = msg.replace(versionRegex, versionPrefix + ' ');
  } else {
    // Prepend valid version
    msg = versionPrefix + ' ' + msg;
  }
  
  fs.writeFileSync(commitMsgFile, msg);
} catch (e) {
  console.error('Failed to prepend version to commit message:', e);
  // Don't fail the commit, just log error
}
